language: node_js

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/coffeeshop_tests

node_js:  
  - "12"

before_script:
  - psql -c 'create database  coffeeshop_tests;' -U postgres
  - psql -U postgres -d coffeeshop_tests -a -f tables.sql

services:
  - postgresql